version: '3.8'

services:
  # Serviço A - Gateway (Input Service)
  otel-gateway:
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ORCHESTRATION_SERVICE_URL=http://otel-orchestration:8081
    depends_on:
      - otel-orchestration
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço B - Orchestration (Weather API)
  otel-orchestration:
    build: 
      context: .
      dockerfile: Dockerfile.orchestration
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=34d03a56db334a6caca234735252207
      - PORT=8081
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
