version: '3.8'

services:
  # Zipkin for distributed tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - otel-network

  # Serviço A - Gateway (Input Service)
  otel-gateway:
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ORCHESTRATION_SERVICE_URL=http://otel-orchestration:8081
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - otel-orchestration
      - zipkin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - otel-network

  # Serviço B - Orchestration (Weather API)
  otel-orchestration:
    build: 
      context: .
      dockerfile: Dockerfile.orchestration
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=34d03a56db334a6caca234735252207
      - PORT=8081
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
