basePath: /
definitions:
  domain.ErrorResponse:
    description: Resposta de erro da API
    properties:
      message:
        example: invalid zipcode
        type: string
    type: object
  domain.WeatherResponse:
    description: Resposta contendo a temperatura em Celsius, Fahrenheit e Kelvin
    properties:
      city:
        example: São Paulo
        type: string
      temp_C:
        example: 28.5
        type: number
      temp_F:
        example: 83.3
        type: number
      temp_K:
        example: 301.5
        type: number
    type: object
  gateway.CEPRequest:
    properties:
      cep:
        type: string
    type: object
  gateway.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: support@otel-orchestration.com
    name: OTEL Orchestration Support
  description: |-
    Serviço de orquestração para consulta de temperatura por CEP brasileiro
    Recebe um CEP válido e retorna a temperatura atual em Celsius, Fahrenheit e Kelvin.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: OTEL Orchestration Service
  version: "1.0"
paths:
  /cep:
    post:
      consumes:
      - application/json
      description: Validates CEP input and forwards to orchestration service
      parameters:
      - description: CEP input
        in: body
        name: cep
        required: true
        schema:
          $ref: '#/definitions/gateway.CEPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response from orchestration service
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/gateway.ErrorResponse'
        "422":
          description: Invalid zipcode
          schema:
            $ref: '#/definitions/gateway.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gateway.ErrorResponse'
      summary: Process CEP input
      tags:
      - gateway
  /health:
    get:
      description: Verifica se a aplicação está funcionando
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /weather/{cep}:
    get:
      consumes:
      - application/json
      description: Recebe um CEP brasileiro válido (já validado pelo Gateway) e retorna
        a temperatura atual em Celsius, Fahrenheit e Kelvin
      parameters:
      - description: CEP brasileiro (8 dígitos, já validado)
        example: '"01310100"'
        in: path
        name: cep
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Informações de temperatura
          schema:
            $ref: '#/definitions/domain.WeatherResponse'
        "404":
          description: CEP não encontrado
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Obter temperatura por CEP
      tags:
      - weather
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Operações relacionadas ao clima
  name: weather
- description: Health check da aplicação
  name: health
